### PR TITLE
renee's changes

### PR DESCRIPTION
**Pull request by reneehlozek**
Hope this works!

### CODE REVIEW

**Comment by reneehlozek** [comment]
Hi @bourque tagging you!

**Review by catherinezucker — APPROVED** [review]
This looks great! My only comment is that you don't necessarily need to import pylab, since it's not used :)

**Comment by bourque** [comment]
Great work! :+1:

**Comment by reneehlozek** [comment]
hi @catherinezucker @bourque 

Well, I tried to include the changes and got this message:

ReneesMacBook:github-401 reneehlozek$ git push
To https://github.com/reneehlozek/github-401.git
 ! [rejected]        reneehlozek-feature -> reneehlozek-feature (non-fast-forward)
error: failed to push some refs to 'https://github.com/reneehlozek/github-401.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
ReneesMacBook:github-401 reneehlozek$ git pull
Already up-to-date.

eeep!

**Pull request merged**
